from enum import StrEnum


class JobType(StrEnum):
    RAG_QUERY = "RAG_QUERY"
    DOCUMENT_INGESTION = "DOCUMENT_INGESTION"
    AGENT_EXECUTION = "AGENT_EXECUTION"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    RETRYING = "RETRYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    DEAD_LETTERED = "DEAD_LETTERED"
    CANCELLED = "CANCELLED"