USER_REGISTERED = "user.registered"
USER_REGISTERED_RETRY = "user.registered.retry"
USER_REGISTERED_DLQ = "user.registered.dlq"
JOB_CREATED = "ai-platform.jobs"
JOB_RETRY = "ai-platform.jobs.retry"
JOB_DLQ = "ai-platform.jobs.dlq"
