"""Add request id to audit logs

Revision ID: bf3d10a639fc
Revises: 824974f0a4aa
Create Date: 2026-06-25 15:42:02.850085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3d10a639fc'
down_revision: Union[str, Sequence[str], None] = '824974f0a4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'request_id')
    # ### end Alembic commands ###
